name: Create Jira issue
on:
  issues:
    types: [opened]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        team_member:
          - { name: "1mjay", JIRA_API_TOKEN: "${{ secrets.JIRA_API_TOKEN_USER1 }}", JIRA_USER_EMAIL: "${{ secrets.JIRA_USER_EMAIL_USER1 }}" }
          # 팀원 추가 예정

    steps:
      - name: Check if issue creator is a team member
        id: check-user
        run: |
          if [[ "${{ github.event.issue.user.login }}" != "${{ matrix.team_member.name }}" ]]; then
            echo "팀원으로 등록되어 있지 않습니다. 계속하려면 팀원으로 추가해주세요."
            exit 1
          fi

      - name: Login to Jira
        if: steps.check-user.outcome == 'success'
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ matrix.team_member.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ matrix.team_member.JIRA_USER_EMAIL }}

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue_form.yml

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: TEST
          issuetype: Sub-task
          summary: "${{ github.event.issue.title }}"
          description: "${{ steps.md2jira.outputs.output-text }}"
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
              }
            }

      - name: Log created issue
        run: echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"
